# 「7章 エラー処理」を読んでの覚書

## 7.1
- スレッド中でパニックしたときに親スレッドから子スレッドがパニックたことを見つける仕組みがあるらしいー>19章


## 7.2 
- Resultの仕組みはだいたいOK
- ?演算子の存在忘れがち
  - Resultを返す関数なら積極的に使うべき
  - 型には注意GenericResult・GenericErrorを定義しておくと楽
- try/catchみたいなことしなくても、Resultで処理結果が明確にわかるの好き
- 基本はすでに存在しているエラーを使うことのが簡単(7.2.5)
  - 標準ライブラリのエラーはBox<dyn std::error::Error + Send + Sync + 'static>;を基底にしてるのでp147のように方エイリアスを定義して::from()メソッドを呼び出すことで変換する->Fromトレイトに関しては13章
  - ただしFromトレイトが実装されていない場合もあるので、thiserrorクレートなどを使ってエラーの実装をする必要がある
- 紹介されていた、anyhow,thiserrorクレートを使って自分でエラー定義の練習する(7.2.5)
- 重要じゃないエラーの握りつぶしは ```let _ = some_result_func()```が便利(7.2.7)
- 疑問：calculate_tides()はどこかで定義してる？(7.2.8)
- ```fn main() -> Result<(),TideCalcError> ```等でResultを返すと標準出力にそのまま出してくれる(7.2.8)
- 自分で出力内容をコントロールしたければ```if let Err(err) =...```でエラー判定してエラー内容を参照できる(7.2.8)
- カスタムエラー型を作る際はErrorトレイトとDisplayトレイトの実装必要
- thiserror便利そう

